stages:
  - prepare
  - build
  - publish

# variable to register in project:
# - DOCKERHUB_URL: url of dockerhub (e.g. docker.io)
# - DOCKERHUB_USER: cytomine username on dockerhub
# - DOCKERHUB_PASSWORD: cytomine password on dockerhub
# - SCRIPTS_REPO_ACCESS_TOKEN_NAME: access token name for docker-entrypoint-scripts repo
# - SCRIPTS_REPO_ACCESS_TOKEN_VALUE: access token value for docker-entrypoint-scripts repo
# - SCRIPTS_REPO_URL: git url (no scheme/protocol) of the docker-entrypoint-scripts repo

variables:
  DOCKER_TMP_IMAGE_NAME: $CI_PIPELINE_ID:latest

default:
  tags:
    - docker

make-version-name:
  stage: prepare
  # regex check does not work with /bin/sh because of parenthesis so we need /bin/bash here
  image: bash:5.2.15-alpine3.16
  script:
    - if [[ "$CI_COMMIT_REF_NAME" =~ ^refs/tags/ ]] then
        echo "CM_VERSION=$CI_COMMIT_TAG" > .env;
      else
        echo "CM_VERSION=$CI_COMMIT_SHORT_SHA-$(date '+%Y%m%d%H%M%S')-SNAPSHOT" > .env;
      fi
    - cat .env
  artifacts:
    reports:
      dotenv: .env

build-docker-image:
  stage: build
  image: docker:latest
  needs:
    - job: make-version-name
      artifacts: true
  script:
    - export BASE_PKG_URL=${CI_API_V4_URL#https://}/packages/npm/
    - docker build -t $DOCKER_TMP_IMAGE_NAME --build-arg JS_CLIENT_REPO_URL=$BASE_PKG_URL --secret "id=js_client_repo_auth_token,env=CI_JOB_TOKEN" -f docker/Dockerfile .

publish-docker-image:
  stage: publish
  image: docker:latest
  needs:
    - job: build-docker-image
      artifacts: false  # artifact are in docker cache (is it a safe assumption in a multi-runner env ?)
    - job: make-version-name
      artifacts: true
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - export DOCKER_IMAGE_NAME_FULL=$CI_REGISTRY_IMAGE:$CM_VERSION
    - docker tag $DOCKER_TMP_IMAGE_NAME $DOCKER_IMAGE_NAME_FULL
    - docker push $DOCKER_IMAGE_NAME_FULL
    - docker rmi $DOCKER_IMAGE_NAME_FULL
  after_script:
    # cleaning up images
    - docker rmi $DOCKER_TMP_IMAGE_NAME

