export default Object.freeze({
    CYTOMINE_CORE_HOST: "http://localhost-core",
    CYTOMINE_UPLOAD_HOST: "http://localhost-upload",
    STOP_PREVIEW_KEYWORD: "STOP_PREVIEW",
    DIGITAL_ZOOM_INCREMENT: 4,
    VIEWER_ANNOTATIONS_REFRESH_INTERVAL: 10000, // ms
    MEMBERS_ACTIVITY_REFRESH_INTERVAL: 30000, // ms
    CONFIG_KEY_WELCOME: "WELCOME"
});
