export default Object.freeze({
    CYTOMINE_CORE_HOST: "localhost-core",
    STOP_PREVIEW_KEYWORD: "STOP_PREVIEW",
    DIGITAL_ZOOM_INCREMENT: 4,
    VIEWER_ANNOTATIONS_REFRESH_INTERVAL: 10000, // ms
});