export default Object.freeze({
    CYTOMINE_CORE_HOST: "http://localhost-core",
    CYTOMINE_UPLOAD_HOST: "http://localhost-upload",
    STOP_PREVIEW_KEYWORD: "STOP_PREVIEW",
    DIGITAL_ZOOM_INCREMENT: 4,
    // Refresh intervals (expressed in milliseconds)
    VIEWER_ANNOTATIONS_REFRESH_INTERVAL: 10000,
    MEMBERS_ACTIVITY_REFRESH_INTERVAL: 30000,
    PING_INTERVAL: 30000,
    JOB_DETAILS_REFRESH_INTERVAL: 2000,
    JOB_DELETION_TASK_REFRESH_INTERVAL: 1000,
    STORAGE_REFRESH_INTERVAL: 10000,
    SAVE_POSITION_IN_IMAGE_INTERVAL: 5000, // position also stored each time the user moves in the image
    BROADCASTING_USERS_REFRESH_INTERVAL: 10000,
    TRACKING_REFRESH_INTERVAL: 500,
    // ---
    CONFIG_KEY_WELCOME: "WELCOME"
});
